name: halco
version: 0.1.0.0
github: "flame-stream/halco"
license: BSD3
author: "Andrey Stoyan"
maintainer: "yukio@yandex-team.ru"
copyright: "2020 Andrey Stoyan"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/flame-stream/halco#readme>

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-unused-imports
  - -Wno-name-shadowing
  - -Wno-unused-matches

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - either
    - containers >= 0.6
    - mtl
    - list-t
    - transformers
    - extra

executables:
  halco-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - halco
      - containers

tests:
  halco-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - halco
      - hspec >= 2.5
      - containers >= 0.6
